### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ripla**
[Review on Reviewable](https://reviewable.io/reviews/saulis/components-1/7)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/Saulis/components-1/pull/7" target="_blank">ReviewNinja

**Comment by Saulis** [comment]
[CLA assistant check](https://cla-assistant.io/Saulis/components-1?pullRequest=7) <br/>All committers have accepted the CLA.

**Comment by Saulis** [comment]
<sup>**[README.md, line 5 [r1]](https://reviewable.io:443/reviews/saulis/components-1/7#-JpBchi-5EugJQmVGbAU)** ([raw file](https://github.com/saulis/components-1/blob/5f9d7ceb5c2743d518f25d30c939699c54bf368a/README.md#L5)):</sup>
It should have at least three RRRs

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/saulis/components-1/7)

**Comment by Saulis** [comment]
Reviewed files:
- README.md @ r1

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/saulis/components-1/7)

**Pull request closed without merging**
